fix get_ip

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -32,7 +32,11 @@ jobs:
         id: get_ip
         run: |
           cd terraform
-          PUBLIC_IP=$(terraform output -raw public_ip | awk '{print $1}')
+          PUBLIC_IP=$(terraform output -raw public_ip | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b")
+          if [[ -z "$PUBLIC_IP" ]]; then
+            echo "Error: No valid IP address found in Terraform output."
+            exit 1
+          fi
           echo "Public IP: $PUBLIC_IP"
           echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV
 
